version: '3.9'
services:
   api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '4000:4000'
    image: app

   production:
    build: 
      context: .
      dockerfile: Dockerfile.prod
    container_name: app_prod
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '5000:5000'
    image: app-production
    
   
